(package "qss-mode"
         "0.1.0"
         "Major mode for Qt Style Sheets")

(website-url "https://github.com/jcs-elpa/qss-mode")
(keywords "languages")

(package-file "qss-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
